import type { Metadata } from "next";
import "./globals.css";
import Background from "@/components/Background";

// メタデータ
export const metadata: Metadata = {
  title: "MyPortfolio",
  description: "Generated by create next app",
};

// レイアウトコンポーネント
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <Background />
        {children}
      </body>
    </html>
  );
}